# Generated by Django 3.1.7 on 2021-03-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('students', models.ManyToManyField(related_name='books', to='school.Student')),
            ],
        ),
    ]
